# Generated by Django 3.1 on 2020-10-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_auto_20201024_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
