# Generated by Django 3.1 on 2020-10-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
