# Generated by Django 3.1 on 2020-10-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0006_auto_20201024_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=22),
        ),
    ]
